#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase
#    username: myuser
#    password: mypassword
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

swagger:
  url: http://localhost:8080 # /swagger-ui/index.html
  description: Local Server URL