server:
  port: 8080

spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/doubleu
    username: root
    password: qwe1212
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true

oauth2:
  google:
    client-id: 595510502221-38jib7lkar5digis4oath7kr6dlglp9v.apps.googleusercontent.com
    client-secret: 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
    scope:
      - email
      - profile

jwt:
  issuer: valvakim@gmail.com
  secret_key: study-springboot

swagger:
  url: http://localhost:8080 # /swagger-ui/index.html
  description: Local Server URL